version: 0.1            # the version of the smart contract
name: my-co         # the name of your continuous organisation
summary: ''             # summary of your organization (optional)
website: ''             # where users can mint/burn tokens (optional)
wallet: ''              # main wallet of the organization
slope: 1.0              # slope of the buying curve
investor_reserve: 0.1   # percentage of invested money put in reserve
revenue_reserve: 0.3    # percentage of revenues put in reserve
initial_tokens: 1000000 # the number of tokens initially available
          